server:
  port: 8084
 
  
spring:
  datasource:
   url: jdbc:postgresql://localhost:5432/microservice
   username: postgres
   password: 8500
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
   
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect:org.hibernate.dialect.PostgreSQL94Dialect
        
  application:
    name: BOOKING-SERVICE 
  config:
    import: optional:configserver:http://localhost:9090

#      
#eureka:
#  instance:
#   prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka